### PR TITLE
Tracking open sockets

### PR DESCRIPTION
**Pull request by zetaben**
Hello, 

These commits create a list of open socket per context. When ruby is freeing things up, the unclosed threads should now be closed first before calling zmq_term. 

I asked for thoughts about this feature on the mailing list :
http://lists.zeromq.org/pipermail/zeromq-dev/2011-October/013814.html

Thanks for the gem

Regards

### CODE REVIEW

**Comment by bwbuchanan** [comment]
This patch needs a lot of cleanup before it can be merged.  The coding style does not match the existing style for the project, and you've rolled your own linked list implementation when it looks like a Ruby array could be used instead.

**Comment by zetaben** [comment]
Yup it most certainly lacks polishing !

I'm curious as to why you would use ruby arrays for the task ? This tracking feature should be an internal mechanism not to be available from ruby.Is that still possible using ruby arrays (I'm completely new at writing C extensions for ruby).

**Comment by bwbuchanan** [comment]
I'm closing this pull request.  The zmq extension now reference counts the 0MQ context and delays terminating it until all sockets are closed (or the ZMQ::Context#close method is explicitly called).

**Comment by zetaben** [comment]
Many thanks for your work on this issue.

**Pull request closed without merging**
